# Generated by Django 5.2.1 on 2025-05-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('episodes', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('members', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='anime.anime')),
            ],
        ),
    ]
